### ISSUE TITLE
Grading job has been scheduled

### ISSUE THREAD

**Issue by rahul26jo** [illinois-cs241/broadway-on-demand#110]
I have only tried to grade an MP but for some reason, it says grading job has been scheduled for both a lab and this MP.

**Comment by Xiangmingchen** [comment]
First of all, a grading job will be shown as scheduled when it is scheduled. It means there are people before you who needs to be graded. Click on the button again sometime later to see the status change. 

Second, please do not use "report issues" when in fact you want to post on piazza. This feature is meant to let you report an actual bug in our web application.

**Comment by rahul26jo** [comment]
The bug I was reporting was that I had only clicked on grade an MP but it also graded my lab when I had not prompted that. I have already mentioned this and felt it was a bug/issue

**Comment by Xiangmingchen** [comment]
Please make a private post on piazza with your netid. We will look into the issue. Also please provide more details about this issue (which timestamp is scheduled for the lab and mp, which lab and mp, etc.)

**Comment by Xiangmingchen** [comment]
Sorry I misinterpreted your issue report because I focused too much on the title instead of the content.

**Comment by rahul26jo** [comment]
Its all good, I understand how hectic your workload must be with all 225 students using this grader. I'll try to make a post later today
