### ISSUE TITLE
Error of make

### ISSUE THREAD

**Issue by xcc990702** [illinois-cs241/broadway-on-demand#114]
<img width="1133" alt="Screen Shot 2020-09-30 at 7 32 36 PM" src="https://user-images.githubusercontent.com/55011046/94680514-6fa2ab80-0354-11eb-8fbd-18d4cbbda2ce.png">
<img width="1434" alt="Screen Shot 2020-09-30 at 7 35 16 PM" src="https://user-images.githubusercontent.com/55011046/94680535-76312300-0354-11eb-9f36-bd63767a2170.png">

I can make my file smoothly on ews, but on autograder it cannot make.

**Comment by Xiangmingchen** [comment]
This is a class-specific problem that is not a bug of on-demand web application. The button "report issue" is not for students who are taking a class to report issues that are specific to a class. Please post in your class's piazza instead.
