### ISSUE TITLE
Edit/Delete Extensions

### ISSUE THREAD

**Issue by rittikaadhikari** [illinois-cs241/broadway-on-demand#120]
It'd be useful to have a button to edit/delete extensions, as it's easy to mistype or accidentally double-submit an extension.

**Comment by Xiangmingchen** [comment]
In the works.
#123

**Comment by Xiangmingchen** [comment]
Btw the double submission was fixed by #121

**Comment by Xiangmingchen** [comment]
Remove extension is done by #123
