### ISSUE TITLE
Nothing happended

### ISSUE THREAD

**Issue by zhekaig2** [illinois-cs241/broadway-on-demand#126]
When I use the broadway to grade my work for cs225 lab_intro, I click the bottom "grade now". Then there is some message telling me that it will take me one chance to grade, and I click ok. But nothing happened. I can't see my grade.

**Comment by rittikaadhikari** [comment]
Hello, 
You should express this concern on the [CS 225 piazza](https://piazza.com/class/kk8qmx7mowj7id), and they will help you.
