### ISSUE TITLE
Exception raised when accessing non-existent course

### ISSUE THREAD

**Issue by nd-0r** [illinois-cs241/broadway-on-demand#159]
When accessing a non-existent course, users get a 500 Internal Server Error. Instead, the user should probably get a 404 page with a descriptive error.

Here are the pertinent parts I think:
https://github.com/illinois-cs241/broadway-on-demand/blob/b930d1fbe6cb49ea4e75ec267d088b3cc334fcda/src/routes_student.py#L28
https://github.com/illinois-cs241/broadway-on-demand/blob/b930d1fbe6cb49ea4e75ec267d088b3cc334fcda/src/db.py#L60

**Comment by ananthm0203** [comment]
Fixed with [this PR](https://github.com/illinois-cs241/broadway-on-demand/pull/162). In the future, we might want to modify the error template a bit for more information, but closing for now.
