### ISSUE TITLE
Automatically update the roster

### ISSUE THREAD

**Issue by bhuvy2** [illinois-cs241/broadway-on-demand#20]
Right now our roster is updated periodically, it'd be nice if the api pulled this updated roster regularly.

**Comment by shreyas208** [comment]
This is definitely nice to have but is kind of CS 241 specific, esp. if it was an automatic thing. It assumes the course has a roster available in some git repository, and would require additional auth stuff to be able to access that repo. Alternatively, what if we had a place on the site where you could upload a roster csv?

**Comment by bhuvy2** [comment]
Sorry I was thinking more along the lines of shibboleth. I know it is a pain, but what could be cool is making a module or service that makes it easier for all courses to get rosters that way.

**Comment by redsn0w422** [comment]
This is definitely more of a Engr IT thing than us, I think waiting for an Official Method™ is probably better. Also shib does not seem easy to work with.

**Comment by bhuvy2** [comment]
I’m worried that since most courses have a hacky solution, we’ll never get a roster.txt again — just another thing for them to build and maintain. I haven’t heard head or tail of a service either before or after git. I’m sure we could twist their arm, but we have the code, we’d just need to codify the registration of a machine to shib once and write the query, then it becomes a simple matter of using OAUTH to check if you are who you say you are and giving you the roster if you are part of a staff list.
