### ISSUE TITLE
Assignment ID Validation

### ISSUE THREAD

**Issue by ayushr2** [illinois-cs241/broadway-on-demand#63]
Currently, the Assignment ID field in the "Add New Assignment" Form allows for whitespaces but that would break things because the assignment ID is part of a URL. Can we prevent spaces from being added by the user?

**Comment by rod-lin** [comment]
Looks like we have already been checking this
https://github.com/illinois-cs241/broadway-on-demand/blob/master/src/routes_staff.py#L52
https://github.com/illinois-cs241/broadway-on-demand/blob/master/src/util.py#L100
