### ISSUE TITLE
Add academic honesty statement to run confirmation

### ISSUE THREAD

**Issue by andyclee** [illinois-cs241/broadway-on-demand#71]
Our academic honesty statement or a similar statement should be included as part of the run confirmation window. Research shows that reminding students of moral obligations and academic honesty policies has significant effects in decreasing academic integrity incidents.

**Comment by ayushr2** [comment]
On-demand is open source and is designed to be used by any course. Having course-specific information hardcoded might not be correct.

If you plan to let the courses using Broadway On-Demand specify the academic honesty statement in the database or something then yes this could be a feasible feature.

I agree with your argument though.

**Comment by andyclee** [comment]
Resolved in latest merge, statement is not specific to course but will move to config later on

**Comment by ayushr2** [comment]
Can we close this?
