### ISSUE TITLE
Case-sensitive to github username

### ISSUE THREAD

**Issue by rod-lin** [illinois-cs241/broadway-on-demand#76]
One student from piazza has a capital letter in her github username(Ritchie5 vs. ritchie5). we should probably take the lower case before inserting usernames into db.

Although I'm not sure what the implication would be. Github is case-sensitive to usernames. Would it be possible for someone to fake other users with a different capitalization?

**Comment by ayushr2** [comment]
If GitHub is case-sensitive to usernames, then we should not be lower casing usernames before adding to DB as it has the scope of breaking things (by using the wrong user).

Any reason you wanted to lower case the username before inserting in DB?

**Comment by ayushr2** [comment]
@rod-lin bump?

**Comment by PradyumnaShome** [comment]
I think we are currently using the NetID as the repository name - we may have to separate those two purposes / store a mapping if they are different?

**Comment by Xiangmingchen** [comment]
Github is case-insensitive. Even though GHE returned a capitalized user name, we can still submit request to it with lower cased names and it will be applied to the same user.
