### ISSUE TITLE
Combine admins and staffs in DB

### ISSUE THREAD

**Issue by ayushr2** [illinois-cs241/broadway-on-demand#87]
Currently, the staff and admins are in separate sets in the DB which can create the possibility for them to diverge. Admins are a strict subset of staff so admin should be a field in the staff ID object.

**Comment by Xiangmingchen** [comment]
I'll need access to the host machine to make changes to the CS241 and ECE411 database.

**Comment by ayushr2** [comment]
Discussing offline.

**Comment by Xiangmingchen** [comment]
Addressed by #128
