### ISSUE TITLE
Forget to commit the code before running autograder

### ISSUE THREAD

**Issue by lijiaxi2018** [illinois-cs241/broadway-on-demand#88]
Hello,

This is Jiaxi Li (netid : jiaxili3). I just submitted an AG but forget to commit my latest code before submitting that autograder. So the AG tested my yesterday's code and I got the same result. I am really sorry for my carelessness and was wondering could you help me run the AG for my code again? (I have already committed and pushed my latest code). I apologized for that but I have spent all the day debugging my code and I really do not want to waste this valuable AG since it is going to the due day. Would you help me run my code again? Thanks!

Best, 

Li Jiaxi

**Comment by aneeshdurg** [comment]
This is not an issue related to this project. Please redirect your course specific questions to a more appropriate forum.

**Comment by PradyumnaShome** [comment]
The appropriate medium for questions like the above is through a Piazza private question/note.
