### ISSUE TITLE
Remove/improve version checking

### ISSUE THREAD

**Issue by rod-lin** [illinois-cs241/broadway-on-demand#89]
Extracting commit hash from the current repo to use as version is a bit ad-hoc. And it doesn't work at all when starting the app from another directory

https://github.com/illinois-cs241/broadway-on-demand/blob/master/src/routes_staff.py#L21

**Comment by ayushr2** [comment]
@rod-lin any solutions for this?

**Comment by Xiangmingchen** [comment]
Resolved by #127
